services:
  back-inventory:
    build:
      context: ./server
    ports:
      - "3040:3040"
    environment:
      - PORT=3040
      - URL_DATABASE=postgres://nwsinventory:nwsinventory@51.75.133.155:5432/nwsinventory
      - NODEMAILER_USER=inv_bb_nws@outlook.fr
      - NODEMAILER_PASS=Zr9(nSb!2Ycm2F+
    # image: ghcr.io/baptiste-boimard/inventaire_nws_back

  front-inventory:
    stdin_open: true
    build:
      context: ./client
    ports:
      - "3100:3100"
    environment:
      - REACT_APP_URL_SERVER=http://51.75.133.155:3040
    # volumes:
    #   - ./ngnix.conf:/etc/nginx/conf.d/default.conf
    # image: ghcr.io/baptiste-boimard/inventaire_nws_front