services:
  back-inventory:
    build:
      context: ./server
    ports:
      - "3040:3040"
    environment:
      - PORT=3040
      - URL_DATABASE=postgres://nwsinventory:nwsinventory@51.75.133.155:5432/nwsinventory
    image: ghcr.io/baptiste-boimard/inventory_nws_back:main

  front-inventory:
    build:
      context: ./client
    ports:
      - "3100:3100"
    environment:
      - REACT_APP_URL_SERVER=http://51.75.133.155:3040
    image: ghcr.io/baptiste-boimard/inventory_nws_front:main