name: inventaire_nws

on: [push]

jobs:
  database:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Npm install
        working-directory: ./server
        run: npm ci

      - name: Connect to Postgresql and create tables
        working-directory: ./server
        run: node ./github/client.js
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          
      - name: Lancement des Tests
        working-directory: ./server
        run: npm test inventoty.test.ts && npm test study.test.ts && npm test loan.test.ts
        env: 
          URL_DATABASE: 'postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable'

  # test:
  #   runs-on: ubuntu-latest
  #   if: github.ref_name == 'main'
