name: inventaire_nws

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        working-directory: ./server
        run: |
          cd server
          npm ci

      - name: Connect to Postgresql
        run: node client.js
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

  # test:
  #   runs-on: ubuntu-latest
  #   if: github.ref_name == 'main'
